spring: 
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
application:
  name: cmpp-gateway
  version: 1.0.0

#gatewar config
gatewar:
  port: 7891
  clientConfig: [{"spIp":"127.0.0.1","spId":"170417","sharedSecret":"170417","spCode":"106584040417","serviceId":"vpass","version":"48"}]